/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 300ea878c225c360007293ed98896ab0)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	ANALYTICS: AnalyticsEngineDataset;
	OPS_RATE_LIMIT_BURST: RateLimit;
	OPS_RATE_LIMIT_SUSTAINED: RateLimit;
	AUTH_RATE_LIMIT_BURST: RateLimit;
	AUTH_EMAIL_RATE_LIMIT: RateLimit;
	CLIENT_ERROR_RATE_LIMIT: RateLimit;
	ANALYTICS_RATE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	ALLOW_LOCAL_ADMIN_AUTH?: "true";
	ACTIVATE_RI_EVENT_ID: "activate-ri-2026";
	ACTIVATE_RI_EMAIL_FROM: "activate-ri-2026@ripota.org";
	ACTIVATE_RI_EMAIL_FROM_NAME: "RI POTA";
	LOCAL_ADMIN_EMAIL?: "local-admin@ripota.org";
	PUBLIC_TURNSTILE_SITE_KEY?: "1x00000000000000000000AA";
	TURNSTILE_REQUIRED: "false" | "true";
	AUTH_ADMIN_MODE: "dual" | "passkey";
	AUTH_ACTIVATOR_MODE: "dual" | "unified";
	AUTH_EMAIL_LOGIN_ENABLED: "true" | "false";
	AUTH_LEGACY_LINK_ISSUANCE_ENABLED: "false" | "true";
	ACTIVATE_RI_OPS_ROOM: DurableObjectNamespace /* ActivateRiOpsRoom */;
	REMOTE_DATA_READ_ONLY?: "true";
	SITE_ORIGIN?: "https://ripota.org";
}
declare namespace Cloudflare {
	interface LocalEnv {
		DB: D1Database;
		EMAIL: SendEmail;
		ANALYTICS: AnalyticsEngineDataset;
		OPS_RATE_LIMIT_BURST: RateLimit;
		OPS_RATE_LIMIT_SUSTAINED: RateLimit;
		AUTH_RATE_LIMIT_BURST: RateLimit;
		AUTH_EMAIL_RATE_LIMIT: RateLimit;
		CLIENT_ERROR_RATE_LIMIT: RateLimit;
		ANALYTICS_RATE_LIMIT: RateLimit;
		ASSETS: Fetcher;
		ALLOW_LOCAL_ADMIN_AUTH: "true";
		ACTIVATE_RI_EVENT_ID: "activate-ri-2026";
		ACTIVATE_RI_EMAIL_FROM: "activate-ri-2026@ripota.org";
		ACTIVATE_RI_EMAIL_FROM_NAME: "RI POTA";
		LOCAL_ADMIN_EMAIL: "local-admin@ripota.org";
		PUBLIC_TURNSTILE_SITE_KEY: "1x00000000000000000000AA";
		TURNSTILE_REQUIRED: "false";
		AUTH_ADMIN_MODE: "dual";
		AUTH_ACTIVATOR_MODE: "dual";
		AUTH_EMAIL_LOGIN_ENABLED: "true";
		AUTH_LEGACY_LINK_ISSUANCE_ENABLED: "false";
		ACTIVATE_RI_OPS_ROOM: DurableObjectNamespace /* ActivateRiOpsRoom */;
	}
	interface ProductionDataEnv {
		DB: D1Database;
		EMAIL: SendEmail;
		ANALYTICS: AnalyticsEngineDataset;
		OPS_RATE_LIMIT_BURST: RateLimit;
		OPS_RATE_LIMIT_SUSTAINED: RateLimit;
		AUTH_RATE_LIMIT_BURST: RateLimit;
		AUTH_EMAIL_RATE_LIMIT: RateLimit;
		CLIENT_ERROR_RATE_LIMIT: RateLimit;
		ANALYTICS_RATE_LIMIT: RateLimit;
		ASSETS: Fetcher;
		ACTIVATE_RI_EVENT_ID: "activate-ri-2026";
		ACTIVATE_RI_EMAIL_FROM: "activate-ri-2026@ripota.org";
		ACTIVATE_RI_EMAIL_FROM_NAME: "RI POTA";
		ALLOW_LOCAL_ADMIN_AUTH: "true";
		LOCAL_ADMIN_EMAIL: "local-admin@ripota.org";
		PUBLIC_TURNSTILE_SITE_KEY: "1x00000000000000000000AA";
		REMOTE_DATA_READ_ONLY: "true";
		TURNSTILE_REQUIRED: "false";
		AUTH_ADMIN_MODE: "dual";
		AUTH_ACTIVATOR_MODE: "dual";
		AUTH_EMAIL_LOGIN_ENABLED: "false";
		AUTH_LEGACY_LINK_ISSUANCE_ENABLED: "true";
		ACTIVATE_RI_OPS_ROOM: DurableObjectNamespace /* ActivateRiOpsRoom */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
